version: 2

references:
  container_config: &container_config
    docker:
      # Main Python container
      - image: circleci/python:3.6.2
        environment:
          TAP_MYSQL_PORT: 3306
          TAP_MYSQL_USER: root
          TAP_MYSQL_PASSWORD: my-secret-passwd
          TAP_MYSQL_HOST: test_mysql

      # MariaDB service container image used as test source database
      - image: mariadb:10.2.26
        name: test_mysql
        environment:
          MYSQL_ROOT_PASSWORD: my-secret-passwd
          MYSQL_DATABASE: tap_mysql_test
        ports:
          - 3306:3306
        command: --default-authentication-plugin=mysql_native_password --log-bin=mysql-bin --binlog-format=ROW

jobs:
  build:
    <<: *container_config

    steps:
      - checkout
      - run:
          name: 'Setup virtual environment'
          command: |
            python3 -m venv ./virtualenvs/tap-mysql
            . ./virtualenvs/tap-mysql/bin/activate
            pip3 install --upgrade pip
            pip3 install -e .[test]
      - run:
          name: 'Pylinting'
          command: |
            . ./virtualenvs/tap-mysql/bin/activate
            pylint --rcfile .pylintrc tap_mysql/
      - run:
          name: 'Tests'
          command: |
            . ./virtualenvs/tap-mysql/bin/activate
            export LOGGING_CONF_FILE=./sample_logging.conf
            nosetests -c .noserc tests

workflows:
  version: 2
  build:
    jobs:
      - build
